# Generated by Django 2.0.5 on 2018-05-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='playlistsongs',
            name='playlist',
            field=models.ManyToManyField(to='home.Playlist'),
        ),
        migrations.AddField(
            model_name='playlistsongs',
            name='song',
            field=models.ManyToManyField(to='home.Song'),
        ),
    ]
