# Generated by Django 2.0.5 on 2018-05-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180521_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
        migrations.AddField(
            model_name='song',
            name='albumArt',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
