# Generated by Django 2.0.5 on 2018-05-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_playlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsongs',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistsongs',
            name='song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='home.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.DeleteModel(
            name='PlaylistSongs',
        ),
    ]
