# Generated by Django 2.0.5 on 2018-05-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180530_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='Unknown Artist', max_length=50),
        ),
    ]
